//! Emit `twofish_vectors.json` for KAT verification.
//!
//! Run from workspace root:
//! `cargo run -p vault --example gen_twofish_vectors > crates/vault/tests/twofish_vectors.json`
//!
//! This is a developer tool; it uses `expect` only here (not in vault library code).

use serde_json::json;
use twofish::cipher::array::Array;
use twofish::cipher::consts::U16;
use twofish::cipher::{BlockCipherEncrypt, KeyInit};
use twofish::Twofish;

fn encrypt_block(key: &[u8], pt: &[u8; 16]) -> [u8; 16] {
    let tf = Twofish::new_from_slice(key).expect("twofish key");
    let block_in: Array<u8, U16> = (*pt).into();
    let mut block_out = Array::<u8, U16>::default();
    tf.encrypt_block_b2b(&block_in, &mut block_out);
    let mut out = [0u8; 16];
    out.copy_from_slice(block_out.as_slice());
    out
}

fn variable_key_chain(key_bits: usize) -> Vec<serde_json::Value> {
    let key_len = key_bits / 8;
    let mut key = vec![0u8; key_len];
    let mut plain = Array::<u8, U16>::default();
    let mut out = Vec::with_capacity(200);
    for i in 1..=200 {
        let plain_in = plain;
        let cipher_arr = {
            let tf = Twofish::new_from_slice(&key).expect("key");
            let block_in: Array<u8, U16> = plain_in.into();
            let mut block_out = Array::<u8, U16>::default();
            tf.encrypt_block_b2b(&block_in, &mut block_out);
            block_out
        };
        out.push(json!({
            "description": format!("variable_key chain iter {i} ({key_bits}-bit key)"),
            "key_bits": key_bits,
            "key": hex::encode(&key),
            "plaintext": hex::encode(plain_in.as_slice()),
            "ciphertext": hex::encode(cipher_arr.as_slice()),
        }));
        if key_len >= 16 {
            let (l, r) = key.split_at_mut(16);
            r.copy_from_slice(&l[..key_len - 16]);
            l.copy_from_slice(plain_in.as_slice());
        }
        plain = cipher_arr;
    }
    out
}

fn variable_text_chain(key_bits: usize) -> Vec<serde_json::Value> {
    let key_len = key_bits / 8;
    let key = vec![0u8; key_len];
    let mut plain = [0u8; 16];
    let mut out = Vec::with_capacity(200);
    for i in 1..=200 {
        let ct = encrypt_block(&key, &plain);
        out.push(json!({
            "description": format!("variable_text chain iter {i} ({key_bits}-bit key)"),
            "key_bits": key_bits,
            "key": hex::encode(&key),
            "plaintext": hex::encode(plain),
            "ciphertext": hex::encode(ct),
        }));
        plain = ct;
    }
    out
}

fn monte_carlo_final_256() -> String {
    let mut key = [0u8; 32];
    let mut plain = Array::<u8, U16>::default();
    for _ in 1..=10_000 {
        let plain_in = plain;
        let tf = Twofish::new_from_slice(&key).expect("key");
        let block_in: Array<u8, U16> = plain_in.into();
        let mut block_out = Array::<u8, U16>::default();
        tf.encrypt_block_b2b(&block_in, &mut block_out);
        let cipher = block_out;
        let (l, r) = key.split_at_mut(16);
        r.copy_from_slice(&l[..16]);
        l.copy_from_slice(plain_in.as_slice());
        plain = cipher;
    }
    hex::encode(plain.as_slice())
}

fn main() {
    let mut vectors: Vec<serde_json::Value> = vec![
        json!({
            "description": "128-bit zero key, zero plaintext",
            "key_bits": 128,
            "key": "00000000000000000000000000000000",
            "plaintext": "00000000000000000000000000000000",
            "ciphertext": "9F589F5CF6122C32B6BFEC2F2AE8C35A",
        }),
        json!({
            "description": "192-bit zero key, zero plaintext",
            "key_bits": 192,
            "key": "000000000000000000000000000000000000000000000000",
            "plaintext": "00000000000000000000000000000000",
            "ciphertext": "EFA71F788965BD4453F860178FC19101",
        }),
        json!({
            "description": "256-bit zero key, zero plaintext",
            "key_bits": 256,
            "key": "0000000000000000000000000000000000000000000000000000000000000000",
            "plaintext": "00000000000000000000000000000000",
            "ciphertext": "57FF739D4DC92C1BD7FC01700CC8216F",
        }),
    ];
    for kb in [128usize, 192, 256] {
        vectors.extend(variable_key_chain(kb));
    }
    for kb in [128usize, 192, 256] {
        vectors.extend(variable_text_chain(kb));
    }
    let mc = monte_carlo_final_256();
    let doc = json!({
        "source": "Twofish specification Appendix B style chains; generated by examples/gen_twofish_vectors.rs using the twofish crate (RustCrypto)",
        "monte_carlo_256_final_ciphertext_hex": mc,
        "vectors": vectors,
    });
    println!("{}", serde_json::to_string_pretty(&doc).expect("json"));
}
